### ISSUE TITLE
Create diagram for phone number algorithm

### ISSUE THREAD

**Issue by YanumVlad** [sergeroshe/Stepik_course#13]

**Comment by sergeroshe** [comment]
https://drive.google.com/file/d/1n_uWbFKNyNWXLFonR4J62jkoe05zz9tf/view?usp=sharing

**Comment by sergeroshe** [comment]
![Valid_number_1_pattern drawio (1)](https://github.com/sergeroshe/Stepik_course/assets/62591932/451af153-cd04-4c69-acae-a3723e4cd250)
