### ISSUE TITLE
15_4_1 Secure Password Generator: program header

### ISSUE THREAD

**Issue by sergeroshe** [sergeroshe/Stepik_course#92]

**Comment by YanumVlad** [comment]
@sergeroshe 
This is a duplicate of the closed PR.
However, what is needed - pls fix the file name of the existing solution in this issue.
[secure_passwd_gen.py](https://github.com/sergeroshe/Stepik_course/blob/main/15_mini_project_work/secure_passwd_gen.py)

Need 4_secure_passwd_gen.py

Please update issue and PR's name, description accordingly
